package up.siscorporativos.docker;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/jogo") // This means URL's start with /amigo (after Application path)
public class MainController {

	@Autowired // This means to get the bean called amigoRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private JogoRepository jogoRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addJogo (@RequestParam String nome
			, @RequestParam String produtora, @RequestParam String plataforma) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Jogo jogo = new Jogo();
		jogo.setNome(nome);
		jogo.setProdutora(produtora);
		jogo.setPlataforma(plataforma);
		jogoRepository.save(jogo);
		return "Jogo cadastrado com sucesso";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Jogo> getJogos() {
		// This returns a JSON or XML with the users
		return jogoRepository.findAll();
	}
}